[package]
name = "rust-part"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate_type = ["cdylib"]


[dependencies]
async-ffi = { version = "0.5.0", features = ["macros", "abi_stable"] }
libc = "0.2.151"
